Support for custom texmf folder
mtneug/texlive-docker pull request #3
Opened 2016-12-03 16:33 UTC by jhoffjann

Added support for custom texmf folder as discussed in #2

2016-12-07 10:47 UTC, mtneug requested changes
Maybe we should add/modify a test document with a texmf tree and a font?

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +  echo "  -i, --init [FILE]     Name of the font to be initialized"
`--map` would probably be a better name (see below)?

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +      "${FILE}.tex"; fi;
Revert the change and export `TEXMFHOME` once in `main`.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +   else bibtex -terse "${FILE}.aux"; fi;
Revert the change and export `TEXMFHOME` once in `main`.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +  && updmap --enable Map "${INIT_FILE}"; fi;\
No need to connect the commands with `&&` when run once in `main` (see below).

After reading up on `mktexlsr` it seams that it should be run after making any changes to the `texmf` tree. So it should be run if `--texmf` is used:

```sh
enableMap() {
  updmap --enable Map "${MAP_FILE}"
}

initTexmf() {
  mktexlsr
}
```

Both should be called once from `main` if needed.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +    && runPdflatex \
Revert change and move `initTexmf` call to `main`. Adding it here will execute `initTexmf` on every run when using `watch`.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> -  echo "      --ignore-errors   Continue watching even if an error occurred"
Please remove trailing whitespace.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +initTexmf(){
Please add a space between `()` and `{`.

2016-12-07 10:47 UTC, mtneug commented on build.sh
> +  else mtexlsr \
`mtexlsr` -> `mktexlsr` :wink:

2016-12-08 10:31 UTC, jhoffjann commented
Now working on this in [texmf](https://github.com/mtneug/texlive-docker/tree/texmf). Check state in #2.

2016-12-08 10:31 UTC, closed without merging